### PR TITLE
Separate stanzas in sequences with newline

### LINKED ISSUE #5: Stanzas in serialized sequences are not separated by an empty line
```rust
let expected = "Package: foo
Description: The Foo

Package: bar
Description: The Bar
";

let values = vec![
    Record {
        package: "foo".to_owned(),
        description:"The Foo".to_owned(),
    },
    Record {
        package: "bar".to_owned(),
        description: "The Bar".to_owned(),
    },
];

assert_eq!(expected, rfc822_like::to_string(&self.val).unwrap()); // Fails

println!("{}", rfc822_like::to_string(&self.val).unwrap());
// Prints
/*
Package: foo
Description: The Foo
Package: bar
Description: The Bar
*/
```

### PR DESCRIPTION
**Pull request by eviltak**
Closes #5

### CODE REVIEW

**Comment by eviltak** [comment]
@Kixunil can you please take a look at this fix and merge (and create a new release) if appropriate? I'm working on a crate that relies on this fix. If you have other things you need to take care of I am happy to offer my services as a maintainer of this crate as well.

**Comment by Kixunil** [comment]
Hey, sorry for so much waiting, I had a lot of stuff going on. Thanks for the PR and the bug report!

**Comment by eviltak** [comment]
No worries, thanks for taking a look at this!

**Comment by Kixunil** [comment]
I've published version 0.2.2

**Pull request merged**
